FROM python:3.8.1

ENV PYTHONUNBUFFERED 1

EXPOSE 8000
WORKDIR /app

RUN pip3 install pipenv

# -- Adding Pipfiles
COPY ./Pipfile Pipfile
COPY ./Pipfile.lock Pipfile.lock

# -- Install dependencies:
RUN set -ex && pipenv install --deploy --system
COPY ./ainapi /app

CMD uvicorn --host=0.0.0.0 --port 8888 main:app

# CMD alembic upgrade head && \
#     uvicorn --host=0.0.0.0 app.main:app
